Repository ALPHAVIO/Mirage-UI, pull requests merged in 2021-07, with the labels that each got.

#122 Fixed glowing gradient button
  HTML+CSS+JS/Buttons/Glowinggradient/index.html
Labels: LGMSOC21, PR: reviewed-approved, 🟪 Level0

#121 fixed mouse enter button
  HTML+CSS+JS/Buttons/MouseenterButton/index.html
Labels: LGMSOC21, PR: reviewed-approved, 🟪 Level0

#124 Drag and drop added
  HTML+CSS+JS/Drag-&-Drop-feature/Drag&Drop/README.md
  HTML+CSS+JS/Drag-&-Drop-feature/Drag&Drop/index.html
  HTML+CSS+JS/Drag-&-Drop-feature/Drag&Drop/script.js
  HTML+CSS+JS/Drag-&-Drop-feature/Drag&Drop/style.css
  HTML+CSS+JS/Drag-&-Drop-feature/Drag&Drop/th.jpg
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#127 Added Zig zag cut design
  HTML+CSS+JS/Background/Zig-Zag-Cut-Design/README.md
  HTML+CSS+JS/Background/Zig-Zag-Cut-Design/index.html
  HTML+CSS+JS/Background/Zig-Zag-Cut-Design/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#132 HTML+CSS+JS/README.md improved
  HTML+CSS+JS/README.md
Labels: PR: reviewed-approved

#131 Timeline component
  HTML+CSS+JS/README.md
  HTML+CSS+JS/Timelines/TimeLineComponent/README.md
  HTML+CSS+JS/Timelines/TimeLineComponent/timeline.css
  HTML+CSS+JS/Timelines/TimeLineComponent/timeline.html
Labels: PR: reviewed-approved

#135 Lines Button Animation
  HTML+CSS+JS/Buttons/LinesButtonAnimation/README.md
  HTML+CSS+JS/Buttons/LinesButtonAnimation/index.html
  HTML+CSS+JS/README.md
Labels: PR: reviewed-approved

#139 Added expand button
  HTML+CSS+JS/Buttons/expand-button/README.md
  HTML+CSS+JS/Buttons/expand-button/index.html
  HTML+CSS+JS/Buttons/expand-button/script.js
  HTML+CSS+JS/Buttons/expand-button/style.css
  HTML+CSS+JS/README.md
Labels: PR: reviewed-approved

#140 fixed stylesheet linking of side top border on hover
  HTML+CSS+JS/Buttons/Sidetopborderonhover/index.html
Labels: LGMSOC21, PR: reviewed-approved, 🟩 Level1

#142 Added flip Button Animation
  HTML+CSS+JS/Buttons/Flip-Button/README.md
  HTML+CSS+JS/Buttons/Flip-Button/index.html
  HTML+CSS+JS/Buttons/Flip-Button/styles.css
  HTML+CSS+JS/README.md
Labels: PR: reviewed-approved

#143 Linear-Icon-Expansion-Animation
  HTML+CSS+JS/Buttons/Linear-Icon-Expansion-Animation/README.md
  HTML+CSS+JS/Buttons/Linear-Icon-Expansion-Animation/index.html
  HTML+CSS+JS/Buttons/Linear-Icon-Expansion-Animation/style.css
  HTML+CSS+JS/README.md
Labels: PR: reviewed-approved

#148 updated readme with opensource program
  README.md
  assets/event1.png
  assets/event2.png
Labels: PR: unreviewed

#149 Added Glassmorphism Animation Form
  HTML+CSS+JS/Forms/Glassmorphism-Form/README.md
  HTML+CSS+JS/Forms/Glassmorphism-Form/index.html
  HTML+CSS+JS/Forms/Glassmorphism-Form/style.css
  HTML+CSS+JS/README.md
Labels: PR: unreviewed

#153 Add Floating Fade Animation Form component
  HTML+CSS+JS/Forms/FloatingFade-AnimationForm/README.md
  HTML+CSS+JS/Forms/FloatingFade-AnimationForm/app.js
  HTML+CSS+JS/Forms/FloatingFade-AnimationForm/form.html
  HTML+CSS+JS/Forms/FloatingFade-AnimationForm/style.css
Labels: PR: unreviewed

#156 modified readme to add contributor
  README.md
Labels: PR: unreviewed

#161 Image-view-stack-carousel
  HTML+CSS+JS/Carousel/Image-view-stack-carousel/README.md
  HTML+CSS+JS/Carousel/Image-view-stack-carousel/assets/1.jpeg
  HTML+CSS+JS/Carousel/Image-view-stack-carousel/assets/2.jpeg
  HTML+CSS+JS/Carousel/Image-view-stack-carousel/assets/3.jpeg
  HTML+CSS+JS/Carousel/Image-view-stack-carousel/assets/4.jpeg
  HTML+CSS+JS/Carousel/Image-view-stack-carousel/assets/5.jpeg
  HTML+CSS+JS/Carousel/Image-view-stack-carousel/assets/6.jpeg
  HTML+CSS+JS/Carousel/Image-view-stack-carousel/index .html
  HTML+CSS+JS/Carousel/Image-view-stack-carousel/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#162 animated card stack animation added
  HTML+CSS+JS/Cards/AnimatedCardStacksAnimation/README.md
  HTML+CSS+JS/Cards/AnimatedCardStacksAnimation/animatedcards.html
  HTML+CSS+JS/Cards/AnimatedCardStacksAnimation/app.js
  HTML+CSS+JS/Cards/AnimatedCardStacksAnimation/lgm.jpeg
  HTML+CSS+JS/Cards/AnimatedCardStacksAnimation/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#165 Added Slide down animation component
  HTML+CSS+JS/Background/Slide-Down-Animation/README.md
  HTML+CSS+JS/Background/Slide-Down-Animation/index.html
  HTML+CSS+JS/Background/Slide-Down-Animation/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#166 Added Accordion Component in the React Section
  React/Accordion/accordion-component/.gitignore
  React/Accordion/accordion-component/.prettierignore
  React/Accordion/accordion-component/README.md
  React/Accordion/accordion-component/package-lock.json
  React/Accordion/accordion-component/package.json
  React/Accordion/accordion-component/public/index.html
  React/Accordion/accordion-component/src/App.js
  React/Accordion/accordion-component/src/components/accordion.js
  React/Accordion/accordion-component/src/index.css
  React/Accordion/accordion-component/src/index.js
  React/Accordion/accordion-component/src/utils/content.js
Labels: PR: reviewed-approved

#168 Tilt-hover-effect
  HTML+CSS+JS/Cards/Tilt-hover-effect/README.md
  HTML+CSS+JS/Cards/Tilt-hover-effect/index.html
  HTML+CSS+JS/Cards/Tilt-hover-effect/style.css
  HTML+CSS+JS/README.md
Labels: PR: reviewed-approved

#174 Added Reveal Page On Hover Navbar component
  HTML+CSS+JS/Navigation-Bar/Reveal-Page-On-Hover-Navbar/README.md
  HTML+CSS+JS/Navigation-Bar/Reveal-Page-On-Hover-Navbar/index.html
  HTML+CSS+JS/Navigation-Bar/Reveal-Page-On-Hover-Navbar/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#178 Logo added
  assets/MUI Logo.png
Labels: PR: unreviewed

#175 Navbar Bubble Animation
  HTML+CSS+JS/Navigation-Bar/Navbar-Bubble-Animation/README.md
  HTML+CSS+JS/Navigation-Bar/Navbar-Bubble-Animation/index.html
  HTML+CSS+JS/Navigation-Bar/Navbar-Bubble-Animation/script.js
  HTML+CSS+JS/Navigation-Bar/Navbar-Bubble-Animation/style.css
  HTML+CSS+JS/README.md
Labels: PR: unreviewed

#180 Image-hover-split-effect
  HTML+CSS+JS/Cards/Image-hover-split-effect/Assests/coder.jpg
  HTML+CSS+JS/Cards/Image-hover-split-effect/README.md
  HTML+CSS+JS/Cards/Image-hover-split-effect/index .html
  HTML+CSS+JS/Cards/Image-hover-split-effect/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#181 Added Auto scrolling background component
  HTML+CSS+JS/Background/Auto-Scrolling-Background/README.md
  HTML+CSS+JS/Background/Auto-Scrolling-Background/assets/MUI Logo.png
  HTML+CSS+JS/Background/Auto-Scrolling-Background/index.html
  HTML+CSS+JS/Background/Auto-Scrolling-Background/style.css
  HTML+CSS+JS/README.md
Labels: PR: partially-approved

#187 Added Rotating Image / Card in React
  React/Card/rotating-image-or-card/.gitignore
  React/Card/rotating-image-or-card/README.md
  React/Card/rotating-image-or-card/package-lock.json
  React/Card/rotating-image-or-card/package.json
  React/Card/rotating-image-or-card/public/favicon.ico
  React/Card/rotating-image-or-card/public/index.html
  React/Card/rotating-image-or-card/src/App.js
  React/Card/rotating-image-or-card/src/Card.js
  React/Card/rotating-image-or-card/src/asset/logo.png
  React/Card/rotating-image-or-card/src/card.css
  React/Card/rotating-image-or-card/src/index.js
  React/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#186 Issue-159 resolved
  HTML+CSS+JS/Image-Animations/ImageOverlayEffects/README.md
  HTML+CSS+JS/Image-Animations/ImageOverlayEffects/index.html
  HTML+CSS+JS/Image-Animations/ImageOverlayEffects/lgm.jpeg
  HTML+CSS+JS/Image-Animations/ImageOverlayEffects/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#190 Icon-hover-expansion
  HTML+CSS+JS/Buttons/Icon-hover-expansion/README.md
  HTML+CSS+JS/Buttons/Icon-hover-expansion/index.html
  HTML+CSS+JS/Buttons/Icon-hover-expansion/style.css
  HTML+CSS+JS/README.md
Labels: PR: reviewed-approved

#192 improved REACT/README.md
  React/README.md
Labels: PR: unreviewed

#195 Added Info card in react
  React/Card/info-card/.gitignore
  React/Card/info-card/README.md
  React/Card/info-card/package-lock.json
  React/Card/info-card/package.json
  React/Card/info-card/public/favicon.ico
  React/Card/info-card/public/index.html
  React/Card/info-card/src/App.js
  React/Card/info-card/src/Card.js
  React/Card/info-card/src/assets/CardIndividual.js
  React/Card/info-card/src/assets/logo.png
  React/Card/info-card/src/card.css
  React/Card/info-card/src/index.js
  React/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#196 Added Bouncing Social Media Icon animation
  HTML+CSS+JS/Footer/Bouncing-Animation/README.md
  HTML+CSS+JS/Footer/Bouncing-Animation/index.html
  HTML+CSS+JS/Footer/Bouncing-Animation/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3
