Repository ALPHAVIO/Mirage-UI, pull requests merged in 2021-06, with the labels that each got.

#5 Update README.md and add actions & workflows
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/assign.yaml
  .github/workflows/autoLabel.yaml
  .github/workflows/review.yml
  README.md
Labels: PR: unreviewed

#18 Add README for components and update styles
  HTML+CSS+JS/Background/Animate.css/README.md
  HTML+CSS+JS/Background/Animate.css/style.css
  HTML+CSS+JS/Background/FakeLoader/1.html
  HTML+CSS+JS/Background/FakeLoader/2.css
  HTML+CSS+JS/Background/FakeLoader/README.md
  HTML+CSS+JS/Background/FakeLoader/app.js
  HTML+CSS+JS/Background/FakeLoader/index.html
  HTML+CSS+JS/Background/FakeLoader/style.css
  HTML+CSS+JS/Background/Particle/README.md
  HTML+CSS+JS/Background/Particle/style.css
  HTML+CSS+JS/Background/SmoothScroll/README.md
  HTML+CSS+JS/Buttons/SnakeBorderButtonAnimation/README.md
  HTML+CSS+JS/Buttons/SnakeBorderButtonAnimation/style.css
Labels: PR: unreviewed

#20 Update style, issue templates and add labelSyncer action
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/labels.json
  .github/workflows/autoLabel.yaml
  .github/workflows/issue-label.yml
  HTML+CSS+JS/Buttons/BlueBackgroundOutButtonAnimation/README.md
  HTML+CSS+JS/Buttons/BlueBackgroundOutButtonAnimation/style.css
  HTML+CSS+JS/Buttons/SnakeBottomBorderOnHover/README.md
  HTML+CSS+JS/Buttons/SnakeBottomBorderOnHover/style.css
  HTML+CSS+JS/Forms/Non-responsveSlidingAnimationForm/README.md
  HTML+CSS+JS/Text-Animations/NumberCounterAnimaton/README.md
  HTML+CSS+JS/Text-Animations/TypeWriterEffect/README.md
  HTML+CSS+JS/Text-Animations/TypeWriterEffect/type.html
  HTML+CSS+JS/Timelines/VerticalTimeline/README.md
  HTML+CSS+JS/Timelines/VerticalTimeline/index.html
  HTML+CSS+JS/jQuery/Jquery-EVENTS/Jquery-fade-toggle-onClick/Jquery fade toggle using button.html
  HTML+CSS+JS/jQuery/Jquery-EVENTS/Jquery-fade-toggle-onClick/README.md
  HTML+CSS+JS/jQuery/Jquery-EVENTS/Jquery-fade-toggle-onHover/Jquery hide and show on mouse hover.html
  HTML+CSS+JS/jQuery/Jquery-EVENTS/Jquery-fade-toggle-onHover/README.md
  HTML+CSS+JS/jQuery/RevealOnScroll/README.md
  HTML+CSS+JS/jQuery/RevealOnScroll/app.js
  HTML+CSS+JS/jQuery/RevealOnScroll/reveal_on_scroll.html
  HTML+CSS+JS/jQuery/RevealOnScroll/style.css
Labels: PR: unreviewed

#19 Adding MIT License #17
  LICENSE
Labels: LGMSOC21, PR: reviewed-approved, 🟩 Level1

#22 Added github actions for level labels
  .github/workflows/level1.yml
  .github/workflows/level2.yml
  .github/workflows/level3.yml
  .github/workflows/level4.yml
Labels: PR: unreviewed

#23 Added Scroll to Top Button
  HTML+CSS+JS/Buttons/scrollToTopButton/README.md
  HTML+CSS+JS/Buttons/scrollToTopButton/button.html
  HTML+CSS+JS/Buttons/scrollToTopButton/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, 🟧 Level3

#25 Fixes issue-2 {added wavy background}
  HTML+CSS+JS/Background/Wavy/README.md
  HTML+CSS+JS/Background/Wavy/wavy.css
  HTML+CSS+JS/Background/Wavy/wavybackground.html
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#21 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: LGMSOC21, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, 🟨 Level2

#31 Readme Improved
  README.md
Labels: PR: unreviewed

#32 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: LGMSOC21, PR: reviewed-changes-requested, PR: unreviewed, 🟨 Level2

#55 Added a side navigation bar component
  HTML+CSS+JS/README.md
  HTML+CSS+JS/Side-Navigation-Bar/README.md
  HTML+CSS+JS/Side-Navigation-Bar/index.css
  HTML+CSS+JS/Side-Navigation-Bar/index.html
Labels: LGMSOC21, PR: reviewed-approved, PR: unreviewed, 🟧 Level3

#53 Added Code of conduct and license
  README.md
Labels: PR: unreviewed, 🟩 Level1

#56 Added a new Button to the HTML+CSS+JS section
  HTML+CSS+JS/Buttons/ElevationOnHoverAnimationButton/README.md
  HTML+CSS+JS/Buttons/ElevationOnHoverAnimationButton/index.html
  HTML+CSS+JS/Buttons/ElevationOnHoverAnimationButton/style.css
  HTML+CSS+JS/README.md
Labels: PR: reviewed-approved

#60 Added Tech Stack
  README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟩 Level1

#59 added Neumorphic styled button
  HTML+CSS+JS/Buttons/NeumorphicStyleButton/README.md
  HTML+CSS+JS/Buttons/NeumorphicStyleButton/index.html
  HTML+CSS+JS/Buttons/NeumorphicStyleButton/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#62 Update README.md
  README.md
Labels: PR: unreviewed

#58 More button animations
  HTML+CSS+JS/Buttons/BlueBackgroundOutButtonAnimation/style.css
  HTML+CSS+JS/Buttons/Glowinggradient/README.md
  HTML+CSS+JS/Buttons/Glowinggradient/index.html
  HTML+CSS+JS/Buttons/Glowinggradient/style.css
  HTML+CSS+JS/Buttons/MouseenterButton/README.md
  HTML+CSS+JS/Buttons/MouseenterButton/index.html
  HTML+CSS+JS/Buttons/MouseenterButton/style.css
  HTML+CSS+JS/Buttons/Sidetopborderonhover/README.md
  HTML+CSS+JS/Buttons/Sidetopborderonhover/index.html
  HTML+CSS+JS/Buttons/Sidetopborderonhover/style.css
  HTML+CSS+JS/Buttons/SnakeBorderButtonAnimation/style.css
  HTML+CSS+JS/Buttons/SnakeBottomBorderOnHover/style.css
  HTML+CSS+JS/Buttons/ThinButton/README.md
  HTML+CSS+JS/Buttons/ThinButton/index.html
  HTML+CSS+JS/Buttons/ThinButton/style.css
  HTML+CSS+JS/Buttons/scrollToTopButton/button.html
  HTML+CSS+JS/Buttons/scrollToTopButton/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟥 Level4

#63 Pranav Singh Maintainer Card Added
  README.md
Labels: PR: unreviewed

#61 code for card pop up animation on hover
  HTML+CSS+JS/Cards/Card Pop up on hover/README.md
  HTML+CSS+JS/Cards/Card Pop up on hover/cardpop.css
  HTML+CSS+JS/Cards/Card Pop up on hover/cardpop.html
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, 🟧 Level3

#69 Akshikamudgal patch 1
  HTML+CSS+JS/Motion Background/README.md
  HTML+CSS+JS/Motion Background/index.html
  HTML+CSS+JS/Motion Background/style.css
  HTML+CSS+JS/Motion Background/used components
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#81 Updated the tech stack
  README.md
Labels: PR: unreviewed

#82 Improved HTML+CSS+JS/README.md
  HTML+CSS+JS/README.md
Labels: PR: unreviewed

#80 carousel component added
  HTML+CSS+JS/Cards/Carouselcomponent/README.md
  HTML+CSS+JS/Cards/Carouselcomponent/index.html
  HTML+CSS+JS/Cards/Carouselcomponent/main.js
  HTML+CSS+JS/Cards/Carouselcomponent/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#64 Readingbar
  HTML+CSS+JS/Cards/Card Pop up on hover/README.md
  HTML+CSS+JS/README.md
  HTML+CSS+JS/ReadingProgressBar/README.md
  HTML+CSS+JS/ReadingProgressBar/ReadingPB.css
  HTML+CSS+JS/ReadingProgressBar/ReadingPB.html
Labels: LGMSOC21, PR: reviewed-approved, PR: unreviewed, 🟧 Level3

#85 Update folder structure and component README
  HTML+CSS+JS/Cards/Card Pop up on hover/README.md
  HTML+CSS+JS/Carousel/CardCarousel/README.md
  HTML+CSS+JS/Carousel/CardCarousel/index.html
  HTML+CSS+JS/Carousel/CardCarousel/main.js
  HTML+CSS+JS/Carousel/CardCarousel/style.css
  HTML+CSS+JS/README.md
  HTML+CSS+JS/Timelines/ReadingProgressBar/README.md
  HTML+CSS+JS/Timelines/ReadingProgressBar/ReadingPB.css
  HTML+CSS+JS/Timelines/ReadingProgressBar/ReadingPB.html
Labels: PR: unreviewed

#87 Added Logo
  README.md
  assets/MIRAGE.gif
Labels: LGMSOC21, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, 🟨 Level2

#89 README.md Updated
  README.md
Labels: PR: unreviewed

#90 Added Ayush Jain as a maintainer
  README.md
Labels: PR: unreviewed

#91 Added Scrollspy Component
  HTML+CSS+JS/README.md
  HTML+CSS+JS/Scrollspy/README.md
  HTML+CSS+JS/Scrollspy/index.html
  HTML+CSS+JS/Scrollspy/style.css
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#95 Modal component
  React/Modal/modal-component/.gitignore
  React/Modal/modal-component/.prettierignore
  React/Modal/modal-component/README.md
  React/Modal/modal-component/package-lock.json
  React/Modal/modal-component/package.json
  React/Modal/modal-component/public/index.html
  React/Modal/modal-component/src/App.js
  React/Modal/modal-component/src/components/Modal.js
  React/Modal/modal-component/src/components/modal.css
  React/Modal/modal-component/src/index.css
  React/Modal/modal-component/src/index.js
  React/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#103 Added Smooth scroll component
  HTML+CSS+JS/README.md
  HTML+CSS+JS/Smooth-Scroll/README.md
  HTML+CSS+JS/Smooth-Scroll/index.html
  HTML+CSS+JS/Smooth-Scroll/style.css
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#105 Update folder Structure
  HTML+CSS+JS/README.md
  HTML+CSS+JS/Scroll/AnimateOnScroll(AOS)/README.md
  HTML+CSS+JS/Scroll/AnimateOnScroll(AOS)/aos.html
  HTML+CSS+JS/Scroll/AnimateOnScroll(AOS)/style.css
  HTML+CSS+JS/Scroll/Scrollspy/README.md
  HTML+CSS+JS/Scroll/Scrollspy/index.html
  HTML+CSS+JS/Scroll/Scrollspy/style.css
  HTML+CSS+JS/Scroll/Smooth-Scroll/README.md
  HTML+CSS+JS/Scroll/Smooth-Scroll/index.html
  HTML+CSS+JS/Scroll/Smooth-Scroll/style.css
  HTML+CSS+JS/Scroll/SmoothPageScroll/README.md
  HTML+CSS+JS/Scroll/SmoothPageScroll/jquery.fullpage.js
  HTML+CSS+JS/Scroll/SmoothPageScroll/scroll.html
  HTML+CSS+JS/Scroll/SmoothPageScroll/style.css
  HTML+CSS+JS/Scroll/scrollToTopButton/README.md
  HTML+CSS+JS/Scroll/scrollToTopButton/button.html
  HTML+CSS+JS/Scroll/scrollToTopButton/style.css
  assets/MIRAGE.gif
Labels: PR: unreviewed

#98 Flip card animation added
  HTML+CSS+JS/Cards/FlipCardAnimation/README.md
  HTML+CSS+JS/Cards/FlipCardAnimation/flipcard.html
  HTML+CSS+JS/Cards/FlipCardAnimation/lgm.jpeg
  HTML+CSS+JS/Cards/FlipCardAnimation/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, PR: unreviewed, 🟧 Level3

#106 Hide and Seek Feature Added
  HTML+CSS+JS/Notifications/Hide-and-seek-notifications/README.md
  HTML+CSS+JS/Notifications/Hide-and-seek-notifications/index.html
  HTML+CSS+JS/Notifications/Hide-and-seek-notifications/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#109 Image bounce animation
  HTML+CSS+JS/Image-Animations/ImageBounceAnimation/README.md
  HTML+CSS+JS/Image-Animations/ImageBounceAnimation/img.png
  HTML+CSS+JS/Image-Animations/ImageBounceAnimation/index.html
  HTML+CSS+JS/Image-Animations/ImageBounceAnimation/style.css
  HTML+CSS+JS/README.md
Labels: PR: reviewed-approved

#112 Modal overlay navbar
  HTML+CSS+JS/Navigation-Bar/Modal-Overlay-Navbar/README.md
  HTML+CSS+JS/Navigation-Bar/Modal-Overlay-Navbar/index.html
  HTML+CSS+JS/Navigation-Bar/Modal-Overlay-Navbar/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#114 Background-motion-mouse-move
  HTML+CSS+JS/Background/Backgound-motion-mouse-move/README.md
  HTML+CSS+JS/Background/Backgound-motion-mouse-move/abstract.png
  HTML+CSS+JS/Background/Backgound-motion-mouse-move/index.html
  HTML+CSS+JS/Background/Backgound-motion-mouse-move/style.css
  HTML+CSS+JS/README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3
